name: Integration Workflow
on:
    push:
        branches-ignore: 
            - main

env:
    PYTHON_VERSION: 3.12

jobs:
    integration-workflow:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
            
            - name: Set up Python ${{ env.PYTHON_VERSION }}
              uses: actions/setup-python@v2
              with:
                python-version: ${{ env.PYTHON_VERSION }}

            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -e .
            
            - name: Run Formatter
              run: |
                black --diff --color --check .

            
